### ISSUE TITLE
Could you please add a screenshot?

### ISSUE THREAD

**Issue by unixorn** [meierjan/nextbike-zsh-theme#1]
Otherwise people need to install it to see what it looks like.

**Comment by meierjan** [comment]
here you go:
![screenscapture](https://cloud.githubusercontent.com/assets/3726563/19215326/1b485068-8d9b-11e6-90e4-43f553823ade.png)

I will add this to to the readme.md soon.

Thanks for the heads up

**Comment by unixorn** [comment]
Cool, adding a link to it to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins)
